# Generated by Django 4.2 on 2025-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=10)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador1', models.CharField(max_length=100)),
                ('jogador2', models.CharField(max_length=100)),
                ('image_j1', models.ImageField(upload_to='images/')),
                ('image_j2', models.ImageField(upload_to='images/')),
                ('jogo1_g1', models.IntegerField()),
                ('jogo2_g1', models.IntegerField()),
                ('jogo1_g2', models.IntegerField()),
                ('jogo2_g2', models.IntegerField()),
                ('vencedor', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pendente', max_length=10)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('preco', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('ultimo_pagamento', models.DateTimeField(auto_now_add=True)),
                ('ranking', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_de_vitorias', models.IntegerField(default=0)),
                ('saldo_games', models.IntegerField(default=0)),
            ],
        ),
    ]
