# Generated by Django 4.2 on 2025-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ultimo_pagamento', models.DateTimeField(auto_now_add=True)),
                ('ranking', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_de_vitorias', models.IntegerField(default=0)),
                ('saldo_games', models.IntegerField(default=0)),
            ],
        ),
    ]
